pod 'Parse'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'ParseUI'
pod 'ParseFacebookUtilsV4'
pod 'TWPhotoPicker', '~> 1.0.0'
pod 'SVPullToRefresh'
pod 'FastttCamera'
pod 'DZNPhotoPickerController'
pod 'InstagramKit', '~> 3.0'
pod 'InstagramKit/UICKeyChainStore'
pod 'JSQMessagesViewController'
pod 'Flurry-iOS-SDK/FlurrySDK'