source "https://github.com/CocoaPods/Old-Specs"

pod 'Parse'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'ParseUI'
pod 'ParseFacebookUtilsV4'
pod 'SVPullToRefresh'
pod 'FastttCamera'
pod 'JSQMessagesViewController', '~> 7.3.3'
pod 'SpinKit', '~> 1.1'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Fabric'
pod 'Crashlytics', '~>  3.8'
pod 'BASSquareCropper', '~> 0.0'
pod 'TOWebViewController', '~> 2.2.6'
pod 'DGActivityIndicatorView'
pod 'HNKGooglePlacesAutocomplete', '~> 1.1'
pod 'ChimpKit'
pod 'QBImagePickerController'
pod 'iCarousel', '~> 1.8'
pod 'BLKFlexibleHeightBar'
pod 'HMSegmentedControl'
pod 'SDWebImage', '~>3.8'
pod 'SwipeView', '~> 1.3'
pod 'FXBlurView', '~> 1.6'
pod 'LXReorderableCollectionViewFlowLayout'
pod 'UIImageView-Letters'
pod 'NMRangeSlider', '~> 1.2'
