source "https://github.com/CocoaPods/Old-Specs"

pod 'Parse'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'ParseUI'
pod 'ParseFacebookUtilsV4'
pod 'SVPullToRefresh'
pod 'FastttCamera'
pod 'JSQMessagesViewController'
pod 'SpinKit', '~> 1.1'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Fabric'
pod 'Crashlytics'
pod 'BASSquareCropper', '~> 0.0'
pod 'TOWebViewController'
pod 'DGActivityIndicatorView'
pod 'iRate', '~> 1.11'
pod 'PulsingHalo'
pod 'HNKGooglePlacesAutocomplete', '~> 1.1'
pod 'ChimpKit'
pod 'QBImagePickerController'
pod 'iCarousel', '~> 1.8'
pod 'BLKFlexibleHeightBar'
pod 'HMSegmentedControl'
